#
# https://docs.travis-ci.com/user/multi-os/
#
language: python

# The build matrix.
matrix:
  include:
    - os: linux
      sudo: required
      env: TOXENV="2.7"
    - os: linux
      sudo: required
      env: TOXENV="3.5"
  
script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    bash ./.travis/linux_test.sh;
    fi

#script:
#  - echo "Testing complete."

branches:
  only:
    - travis_osx

notifications:
  email:
    recipients:
      - hbabcock@mac.com
    on_success: never
    on_failure: never
