
branches:
  only:
    - master
    
environment:
    
  matrix:
    - JOB: "2.7 64-bit"
      MINICONDA: "C:\\Miniconda-x64"
      PYVERSION: "2.7"

    - JOB: "3.6 64-bit"
      MINICONDA: "C:\\Miniconda36-x64"
      PYVERSION: "3.6"

install:

  # Configure conda Python environment.
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;C:\\Windows\\system32;C:\\Windows;"
  - "conda --version"
  - "conda create --yes --name saenv python=%PYVERSION%"
  - "activate saenv"
  - "conda config --add channels conda-forge"
  - "conda install --yes numpy pytest pytest-runner"
  - "conda install --yes m2w64-toolchain tifffile scipy h5py astropy"
  - "conda install --yes matplotlib pillow shapely randomcolor pywavelets"
  - "conda install --yes scons"
  
  # Install storm-analysis
  - "scons -Q compiler=mingw"
  - "python setup.py install"

build: off

test_script:
  - "python setup.py test"

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*
